import { Card, SourceDoc } from '../types'

const TYPE_EMOJI: Record<string, string> = {
  concept: '◆',
  definition: '§',
  fact: '#',
  step: '»',
  quote: '"',
  question: '?',
}

export function toMarkdown(docs: SourceDoc[], cards: Card[]): string {
  const byDoc = new Map<string, Card[]>()
  for (const c of cards) {
    if (c.status === 'hidden') continue
    const arr = byDoc.get(c.sourceId) || []
    arr.push(c)
    byDoc.set(c.sourceId, arr)
  }
  const out: string[] = ['# Synth — knowledge cards', '']
  for (const doc of docs) {
    const list = byDoc.get(doc.id)
    if (!list?.length) continue
    out.push(`## ${doc.title}`, '')
    for (const c of list) {
      out.push(`### ${TYPE_EMOJI[c.type] ?? '◆'} ${c.title}`)
      out.push('')
      if (c.summary) out.push(c.summary, '')
      for (const b of c.bullets) out.push(`- ${b}`)
      if (c.bullets.length) out.push('')
      if (c.tags.length) out.push(c.tags.map((t) => `#${t.replace(/\s+/g, '-')}`).join(' '), '')
      out.push('---', '')
    }
  }
  out.push(`> Generated by Synth · ${new Date().toISOString().slice(0, 10)}`)
  return out.join('\n')
}

function ankiField(s: string): string {
  return s.replace(/\t/g, ' ').replace(/\r?\n/g, '<br>').replace(/"/g, '""')
}

/**
 * Anki-importable TSV. Import with "Fields separated by: Tab" and
 * "Allow HTML in fields" checked.
 */
export function toAnkiTsv(cards: Card[]): string {
  const rows = ['#separator:tab', '#html:true', '#tags column:3']
  for (const c of cards) {
    if (c.status === 'hidden') continue
    const back = [c.summary, ...c.bullets.map((b) => `• ${b}`)].filter(Boolean).join('<br>')
    rows.push(
      [ankiField(c.title), ankiField(back), c.tags.map((t) => t.replace(/\s+/g, '_')).join(' ')].join(
        '\t',
      ),
    )
  }
  return rows.join('\n')
}

export function toJson(docs: SourceDoc[], cards: Card[]): string {
  return JSON.stringify({ app: 'synth', version: 2, exportedAt: Date.now(), docs, cards }, null, 2)
}

export function download(filename: string, content: string | Blob, mime = 'text/plain'): void {
  const blob = typeof content === 'string' ? new Blob([content], { type: `${mime};charset=utf-8` }) : content
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function slugify(s: string): string {
  return (
    s
      .trim()
      .replace(/[\\/:*?"<>|]+/g, '')
      .replace(/\s+/g, '-')
      .slice(0, 48) || 'synth'
  )
}

/* ------------------------------------------------------------------ */
/* Share image                                                         */
/* ------------------------------------------------------------------ */

const FONT_STACK =
  '-apple-system, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans", "Microsoft YaHei", sans-serif'

function wrapTokens(text: string): string[] {
  // CJK chars break anywhere; latin words stay atomic.
  return text.match(/[\u4e00-\u9fa5\u3040-\u30ff\u3000-\u303f]|[^\s\u4e00-\u9fa5\u3040-\u30ff]+|\s+/g) ?? []
}

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const tokens = wrapTokens(text)
  const lines: string[] = []
  let line = ''
  for (const tk of tokens) {
    const test = line + tk
    if (ctx.measureText(test).width > maxWidth && line.trim()) {
      lines.push(line.trimEnd())
      line = tk.trimStart()
    } else {
      line = test
    }
  }
  if (line.trim()) lines.push(line.trimEnd())
  return lines
}

export interface PngOptions {
  width?: number
  dark?: boolean
  footer?: string
}

/** Render a single card to a shareable PNG (no external dependency). */
export async function cardToPng(card: Card, opts: PngOptions = {}): Promise<Blob> {
  const W = opts.width ?? 1080
  const pad = 72
  const dark = opts.dark ?? true
  const measure = document.createElement('canvas').getContext('2d')
  if (!measure) throw new Error('Canvas unsupported')

  const inner = W - pad * 2
  measure.font = `700 52px ${FONT_STACK}`
  const titleLines = wrapText(measure, card.title, inner)
  measure.font = `400 30px ${FONT_STACK}`
  const summaryLines = wrapText(measure, card.summary, inner)
  const bulletLines: string[][] = card.bullets.map((b) => wrapText(measure, b, inner - 34))

  let H = pad + 46 + titleLines.length * 66 + 24 + summaryLines.length * 46 + 18
  for (const bl of bulletLines) H += bl.length * 42 + 12
  H += 40 + (card.tags.length ? 46 : 0) + pad

  const canvas = document.createElement('canvas')
  canvas.width = W
  canvas.height = Math.max(H, 560)
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('Canvas unsupported')

  const bg = ctx.createLinearGradient(0, 0, W, canvas.height)
  if (dark) {
    bg.addColorStop(0, '#12151c')
    bg.addColorStop(1, '#1b2130')
  } else {
    bg.addColorStop(0, '#ffffff')
    bg.addColorStop(1, '#eef2f8')
  }
  ctx.fillStyle = bg
  ctx.fillRect(0, 0, W, canvas.height)

  const accent = '#6ea8fe'
  ctx.fillStyle = accent
  ctx.fillRect(0, 0, 10, canvas.height)

  let y = pad + 8
  ctx.font = `600 24px ${FONT_STACK}`
  ctx.fillStyle = accent
  ctx.fillText(card.type.toUpperCase(), pad, y)
  y += 56

  ctx.font = `700 52px ${FONT_STACK}`
  ctx.fillStyle = dark ? '#eef3fb' : '#10141c'
  for (const l of titleLines) {
    ctx.fillText(l, pad, y)
    y += 66
  }
  y += 18

  ctx.font = `400 30px ${FONT_STACK}`
  ctx.fillStyle = dark ? '#c3ccdb' : '#2b3648'
  for (const l of summaryLines) {
    ctx.fillText(l, pad, y)
    y += 46
  }
  y += 14

  ctx.font = `400 28px ${FONT_STACK}`
  ctx.fillStyle = dark ? '#9aa6ba' : '#4a5568'
  for (const bl of bulletLines) {
    ctx.fillStyle = accent
    ctx.fillText('•', pad, y)
    ctx.fillStyle = dark ? '#9aa6ba' : '#4a5568'
    for (const l of bl) {
      ctx.fillText(l, pad + 34, y)
      y += 42
    }
    y += 12
  }

  if (card.tags.length) {
    y += 8
    ctx.font = `500 26px ${FONT_STACK}`
    ctx.fillStyle = accent
    ctx.fillText(card.tags.map((t) => `#${t}`).join('  '), pad, y)
  }

  ctx.font = `500 24px ${FONT_STACK}`
  ctx.fillStyle = dark ? '#6b768a' : '#8892a4'
  ctx.fillText(opts.footer ?? 'Made with Synth · local-first study cards', pad, canvas.height - 42)

  return await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('toBlob failed'))), 'image/png')
  })
}
